version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    networks:
      - lol-app-network
    healthcheck:
      test: echo exit | mongosh || exit 1
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 30s


  spring-boot-app:
    image: project-backend:${PROJECT_BACKEND_TAG-latest}
    container_name: spring-boot-app
    build:
      context: .
      tags:
        - "project-backend:latest"
    restart: always
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:examplepassword@mongodb:27017/database
      JWT_SECRET: ${JWT_SECRET-test}
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      lol-app-network:
        aliases:
          - backend

networks:
  lol-app-network:
    name: lol-app-network

