version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    networks:
      - mynetwork

  spring-boot-app:
    image: project-backend
    container_name: spring-boot-app
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:examplepassword@mongodb:27017/database
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

