spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      authentication-database: admin
      username: root
      password: password
token:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationMs: 3600000