name: backend-build-and-run
on:
  push:
    branches:
      - add-github-actions
jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build
        run: docker build -t project-backend:latest .

      - name: compose
        run: docker-compose up --build